name: dicery
description: Roll dice with friends.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  animated_text_kit: ^2.2.0
  numberpicker: ^1.2.0
  timeago_flutter: ^0.1.0
  provider: ^4.1.3
  
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.9.0

flutter:
  uses-material-design: true
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Regular.ttf
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto_Mono/RobotoMono-Thin.ttf
          weight: 100
